 version: '2'

 networks:
   fabric-network:

 services:
   orderer0.bi.example.com:
     container_name: orderer0.bi.example.com
     image: hyperledger/fabric-orderer:latest
     environment:
       - ORDERER_GENERAL_LOGLEVEL=info
       - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
       - ORDERER_GENERAL_GENESISMETHOD=file
       - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/orderer.genesis.block
       - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
       - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
       - ORDERER_GENERAL_TLS_ENABLED=true
       - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
       - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
       - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
     volumes:
       - ./crypto-config/ordererOrganizations/bi.example.com/orderers/orderer0.bi.example.com/msp:/var/hyperledger/orderer/msp
       - ./crypto-config/ordererOrganizations/bi.example.com/orderers/orderer0.bi.example.com/tls:/var/hyperledger/orderer/tls
       - ./channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
     ports:
       - 7050:7050
     networks:
       - fabric-network

   orderer1.bi.example.com:
     container_name: orderer1.bi.example.com
     image: hyperledger/fabric-orderer:latest
     environment:
       - ORDERER_GENERAL_LOGLEVEL=info
       - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
       - ORDERER_GENERAL_GENESISMETHOD=file
       - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/orderer.genesis.block
       - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
       - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
       - ORDERER_GENERAL_TLS_ENABLED=true
       - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
       - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
       - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
     volumes:
       - ./crypto-config/ordererOrganizations/bi.example.com/orderers/orderer1.bi.example.com/msp:/var/hyperledger/orderer/msp
       - ./crypto-config/ordererOrganizations/bi.example.com/orderers/orderer1.bi.example.com/tls:/var/hyperledger/orderer/tls
       - ./channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
     ports:
       - 8050:7050
     networks:
       - fabric-network

   orderer2.bi.example.com:
     container_name: orderer2.bi.example.com
     image: hyperledger/fabric-orderer:latest
     environment:
       - ORDERER_GENERAL_LOGLEVEL=info
       - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
       - ORDERER_GENERAL_GENESISMETHOD=file
       - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/orderer.genesis.block
       - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
       - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
       - ORDERER_GENERAL_TLS_ENABLED=true
       - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
       - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
       - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
     volumes:
       - ./crypto-config/ordererOrganizations/bi.example.com/orderers/orderer2.bi.example.com/msp:/var/hyperledger/orderer/msp
       - ./crypto-config/ordererOrganizations/bi.example.com/orderers/orderer2.bi.example.com/tls:/var/hyperledger/orderer/tls
       - ./channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
     ports:
       - 9050:7050
     networks:
       - fabric-network

   peer0.dana.example.com:
     container_name: peer0.dana.example.com
     image: hyperledger/fabric-peer:latest
     environment:
       - CORE_PEER_ID=peer0.dana.example.com
       - CORE_PEER_LOCALMSPID=DanaMSP
       - CORE_PEER_ADDRESS=peer0.dana.example.com:7051
       - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
       - CORE_PEER_CHAINCODEADDRESS=peer0.dana.example.com:7052
       - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
       - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
       - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.dana.example.com:8051
       - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.dana.example.com:7051
       - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=fabric-network
     volumes:
       - /var/run/docker.sock:/host/var/run/docker.sock
       - ./crypto-config/peerOrganizations/dana.example.com/peers/peer0.dana.example.com/msp:/etc/hyperledger/fabric/msp
       - ./crypto-config/peerOrganizations/dana.example.com/peers/peer0.dana.example.com/tls:/etc/hyperledger/fabric/tls
     ports:
       - 7051:7051
     networks:
       - fabric-network

   peer1.dana.example.com:
     container_name: peer1.dana.example.com
     image: hyperledger/fabric-peer:latest
     environment:
       - CORE_PEER_ID=peer1.dana.example.com
       - CORE_PEER_LOCALMSPID=DanaMSP
       - CORE_PEER_ADDRESS=peer1.dana.example.com:8051
       - CORE_PEER_LISTENADDRESS=0.0.0.0:8051
       - CORE_PEER_CHAINCODEADDRESS=peer1.dana.example.com:8052
       - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:8052
       - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
       - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.dana.example.com:7051
       - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.dana.example.com:8051
       - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=fabric-network
     volumes:
       - /var/run/docker.sock:/host/var/run/docker.sock
       - ./crypto-config/peerOrganizations/dana.example.com/peers/peer1.dana.example.com/msp:/etc/hyperledger/fabric/msp
       - ./crypto-config/peerOrganizations/dana.example.com/peers/peer1.dana.example.com/tls:/etc/hyperledger/fabric/tls
     ports:
       - 8051:8051
     networks:
       - fabric-network

   peer0.gopay.example.com:
     container_name: peer0.gopay.example.com
     image: hyperledger/fabric-peer:latest
     environment:
       - CORE_PEER_ID=peer0.gopay.example.com
       - CORE_PEER_LOCALMSPID=GopayMSP
       - CORE_PEER_ADDRESS=peer0.gopay.example.com:9051
       - CORE_PEER_LISTENADDRESS=0.0.0.0:9051
       - CORE_PEER_CHAINCODEADDRESS=peer0.gopay.example.com:9052
       - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:9052
       - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
       - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.gopay.example.com:10051
       - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.gopay.example.com:9051
       - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=fabric-network
     volumes:
       - /var/run/docker.sock:/host/var/run/docker.sock
       - ./crypto-config/peerOrganizations/gopay.example.com/peers/peer0.gopay.example.com/msp:/etc/hyperledger/fabric/msp
       - ./crypto-config/peerOrganizations/gopay.example.com/peers/peer0.gopay.example.com/tls:/etc/hyperledger/fabric/tls
     ports:
       - 9051:9051
     networks:
       - fabric-network

   peer1.gopay.example.com:
     container_name: peer1.gopay.example.com
     image: hyperledger/fabric-peer:latest
     environment:
       - CORE_PEER_ID=peer1.gopay.example.com
       - CORE_PEER_LOCALMSPID=GopayMSP
       - CORE_PEER_ADDRESS=peer1.gopay.example.com:10051
       - CORE_PEER_LISTENADDRESS=0.0.0.0:10051
       - CORE_PEER_CHAINCODEADDRESS=peer1.gopay.example.com:10052
       - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:10052
       - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
       - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.gopay.example.com:9051
       - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.gopay.example.com:10051
       - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=fabric-network
     volumes:
       - /var/run/docker.sock:/host/var/run/docker.sock
       - ./crypto-config/peerOrganizations/gopay.example.com/peers/peer1.gopay.example.com/msp:/etc/hyperledger/fabric/msp
       - ./crypto-config/peerOrganizations/gopay.example.com/peers/peer1.gopay.example.com/tls:/etc/hyperledger/fabric/tls
     ports:
       - 10051:10051
     networks:
       - fabric-network




